name: Build and test

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

env:
  NODE_VERSION: '16.14.0'                # set this to the node version to use

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: go, javascript
    - name: npm install, build, and test
      run: |
        # Build and test the project
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: src
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
